// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SmokeTestHelperProject.SmokeTestHelperClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class SmokeTestHelper
    {
        
        #region Properties
        public UIAa1WelcometoPOMSnetWWindow UIAa1WelcometoPOMSnetWWindow
        {
            get
            {
                if ((this.mUIAa1WelcometoPOMSnetWWindow == null))
                {
                    this.mUIAa1WelcometoPOMSnetWWindow = new UIAa1WelcometoPOMSnetWWindow();
                }
                return this.mUIAa1WelcometoPOMSnetWWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIAa1WelcometoPOMSnetWWindow mUIAa1WelcometoPOMSnetWWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIAa1WelcometoPOMSnetWWindow : BrowserWindow
    {
        
        public UIAa1WelcometoPOMSnetWWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "[aa1] - Welcome to POMSnet";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("[aa1] - Welcome to POMSnet");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAa1WelcometoPOMSnetDocument UIAa1WelcometoPOMSnetDocument
        {
            get
            {
                if ((this.mUIAa1WelcometoPOMSnetDocument == null))
                {
                    this.mUIAa1WelcometoPOMSnetDocument = new UIAa1WelcometoPOMSnetDocument(this);
                }
                return this.mUIAa1WelcometoPOMSnetDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIAa1WelcometoPOMSnetDocument mUIAa1WelcometoPOMSnetDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIAa1WelcometoPOMSnetDocument : HtmlDocument
    {
        
        public UIAa1WelcometoPOMSnetDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "[aa1] - Welcome to POMSnet";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Hoops/Welcome.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://va24-pd-r340w/Hoops/Welcome.aspx";
            this.WindowTitles.Add("[aa1] - Welcome to POMSnet");
            #endregion
        }
        
        #region Properties
        public UIForm1Custom UIForm1Custom
        {
            get
            {
                if ((this.mUIForm1Custom == null))
                {
                    this.mUIForm1Custom = new UIForm1Custom(this);
                }
                return this.mUIForm1Custom;
            }
        }
        #endregion
        
        #region Fields
        private UIForm1Custom mUIForm1Custom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIForm1Custom : HtmlCustom
    {
        
        public UIForm1Custom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "Form1";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=Form1 method=post action=Welcome.aspx";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("[aa1] - Welcome to POMSnet");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIHoneywellImage
        {
            get
            {
                if ((this.mUIHoneywellImage == null))
                {
                    this.mUIHoneywellImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIHoneywellImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIHoneywellImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIHoneywellImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Honeywell";
                    this.mUIHoneywellImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/HOOPS/images/honeywell_logo.jpg";
                    this.mUIHoneywellImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://va24-pd-r340w/HOOPS/images/honeywell_logo.jpg";
                    this.mUIHoneywellImage.FilterProperties[HtmlImage.PropertyNames.Class] = "noflip";
                    this.mUIHoneywellImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "class=noflip alt=Honeywell src=\"/HOOPS/i";
                    this.mUIHoneywellImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIHoneywellImage.WindowTitles.Add("[aa1] - Welcome to POMSnet");
                    #endregion
                }
                return this.mUIHoneywellImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIHoneywellImage;
        #endregion
    }
}
