// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            HtmlEdit uIQEdit = this.UIMSNcomHotmailOutlookWindow.UIMSNcomHotmailOutlookDocument.UIQEdit;
            HtmlButton uIWebsearchButton = this.UIMSNcomHotmailOutlookWindow.UIMSNcomHotmailOutlookDocument.UIWebsearchButton;
            #endregion

            // Type 'test' in 'q' text box
            uIQEdit.Text = this.RecordedMethod1Params.UIQEditText;

            // Click 'web search' button
            Mouse.Click(uIWebsearchButton, new Point(40, 24));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIMSNcomHotmailOutlookWindow UIMSNcomHotmailOutlookWindow
        {
            get
            {
                if ((this.mUIMSNcomHotmailOutlookWindow == null))
                {
                    this.mUIMSNcomHotmailOutlookWindow = new UIMSNcomHotmailOutlookWindow();
                }
                return this.mUIMSNcomHotmailOutlookWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIMSNcomHotmailOutlookWindow mUIMSNcomHotmailOutlookWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'test' in 'q' text box
        /// </summary>
        public string UIQEditText = "test";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMSNcomHotmailOutlookWindow : BrowserWindow
    {
        
        public UIMSNcomHotmailOutlookWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
            this.WindowTitles.Add("test - Bing");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIMSNcomHotmailOutlookDocument UIMSNcomHotmailOutlookDocument
        {
            get
            {
                if ((this.mUIMSNcomHotmailOutlookDocument == null))
                {
                    this.mUIMSNcomHotmailOutlookDocument = new UIMSNcomHotmailOutlookDocument(this);
                }
                return this.mUIMSNcomHotmailOutlookDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMSNcomHotmailOutlookDocument mUIMSNcomHotmailOutlookDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMSNcomHotmailOutlookDocument : HtmlDocument
    {
        
        public UIMSNcomHotmailOutlookDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.msn.com/?ocid=iehp";
            this.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIQEdit
        {
            get
            {
                if ((this.mUIQEdit == null))
                {
                    this.mUIQEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIQEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "q";
                    this.mUIQEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "q";
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"q\" id=\"q\" accesskey=\"S\" aria-label";
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIQEdit.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
                    #endregion
                }
                return this.mUIQEdit;
            }
        }
        
        public HtmlButton UIWebsearchButton
        {
            get
            {
                if ((this.mUIWebsearchButton == null))
                {
                    this.mUIWebsearchButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIWebsearchButton.SearchProperties[HtmlButton.PropertyNames.Id] = "sb_form_go";
                    this.mUIWebsearchButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIWebsearchButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "web search";
                    this.mUIWebsearchButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIWebsearchButton.FilterProperties[HtmlButton.PropertyNames.Title] = "web search";
                    this.mUIWebsearchButton.FilterProperties[HtmlButton.PropertyNames.Class] = "text";
                    this.mUIWebsearchButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "title=\"web search\" class=\"text\" id=\"sb_f";
                    this.mUIWebsearchButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUIWebsearchButton.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
                    #endregion
                }
                return this.mUIWebsearchButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIQEdit;
        
        private HtmlButton mUIWebsearchButton;
        #endregion
    }
}
